In [1]:
import numpy as np
data= np.array([
    [10,1000],
    [20,2000],
    [30,3000]
])
print(data.ndim)
print(data.dtype)
print(data.shape)
print(data.size)

2
int64
(3, 2)
6


In [1]:
import numpy as np
number= np.array([1,2,3,4,5])
results=number*100
print(results)
# results>30
results[(results>300) & (results<500)]

[100 200 300 400 500]


array([400])

In [2]:
price= np.array([100,200,300])
quantity= np.array([2,4,6])
price*quantity

array([ 200,  800, 1800])

In [5]:
arr= np.array([
    [1,2,3],
    [4,5,6]
])
# arr.reshape(1,6)
arr.reshape(-1) #reshaping 2d array into 1d

array([1, 2, 3, 4, 5, 6])