In [2]:
import numpy as np
age= np.array([10,20,30])
age


roll_no=np.array([11,22,33])
roll_no


array([11, 22, 33])

In [3]:
student= np.array([
    [20,30,40],
    [10,12,14]
])
print(student)

[[20 30 40]
 [10 12 14]]


In [4]:
student_data= np.array([12,90])
weights= np.array([10,2])
prediction= np.dot(student_data,weights)
print(prediction)

300


In [5]:
data= np.array([
    [12,90],
    [14,80],
    [16,50]
])
weight= np.array([[10],[2]])
pr= np.dot(data,weight)
print(pr)

[[300]
 [300]
 [260]]
