In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

In [2]:
df = pd.read_csv("Question2.csv")

print(df.head())

  Student  Attendance  MathScore  EnglishScore  QuizScore  MissedClasses  \
0   Aarav          72         55            58         61              1   
1    Sita          91         86            84         88              0   
2     Ram          68         48            52         55              4   
3  Anisha          94         92            89         91              0   
4   Rohan          75         60            57         63              2   

   MathSupport  EnglishSupport  AttendanceSupport  
0            0               1                  0  
1            0               0                  0  
2            1               1                  0  
3            0               0                  0  
4            0               1                  0  


In [3]:
print(df.shape)
print(df.columns)
print(df.info())
print(df.isnull().sum())

(20, 9)
Index(['Student', 'Attendance', 'MathScore', 'EnglishScore', 'QuizScore',
       'MissedClasses', 'MathSupport', 'EnglishSupport', 'AttendanceSupport'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student            20 non-null     str  
 1   Attendance         20 non-null     int64
 2   MathScore          20 non-null     int64
 3   EnglishScore       20 non-null     int64
 4   QuizScore          20 non-null     int64
 5   MissedClasses      20 non-null     int64
 6   MathSupport        20 non-null     int64
 7   EnglishSupport     20 non-null     int64
 8   AttendanceSupport  20 non-null     int64
dtypes: int64(8), str(1)
memory usage: 1.5 KB
None
Student              0
Attendance           0
MathScore            0
EnglishScore         0
QuizScore            0
MissedClasses        0
MathSupport          0
EnglishSupp

In [5]:
X = df[
    [
       "Attendance",
        "MathScore",
        "EnglishScore",
        "QuizScore",
        "MissedClasses"
        
    ]
]
y = df[
    [
        "MathSupport",
        "EnglishSupport",
        "AttendanceSupport"
    ]
]
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
model = OneVsRestClassifier(
    LogisticRegression()
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(y_pred)

[[1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.75


In [7]:
precision = precision_score(
    y_test,
    y_pred,
    average="micro"
)

print("Precision:", precision)

Precision: 0.5


In [8]:
recall = recall_score(
    y_test,
    y_pred,
    average="micro"
)

print("Recall:", recall)

Recall: 1.0


In [9]:
f1 = f1_score(
    y_test,
    y_pred,
    average="micro"
)

print("F1 Score:", f1)

F1 Score: 0.6666666666666666


In [10]:
print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "Math Support",
            "English Support",
            "Attendance Support"
        ]
    )
)

                    precision    recall  f1-score   support

      Math Support       0.00      0.00      0.00         0
   English Support       1.00      1.00      1.00         1
Attendance Support       0.00      0.00      0.00         0

         micro avg       0.50      1.00      0.67         1
         macro avg       0.33      0.33      0.33         1
      weighted avg       1.00      1.00      1.00         1
       samples avg       0.12      0.25      0.17         1



C:\Users\misti\OneDrive\Desktop\AI\aiudaan\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\misti\OneDrive\Desktop\AI\aiudaan\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\misti\OneDrive\Desktop\AI\aiudaan\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize(

In [11]:
for i, prediction in enumerate(y_pred):
    print(f"\nStudent {i+1} Support Prediction:")

    print(
        "Math Support:",
        "Yes" if prediction[0] == 1 else "No"
    )

    print(
        "English Support:",
        "Yes" if prediction[1] == 1 else "No"
    )

    print(
        "Attendance Support:",
        "Yes" if prediction[2] == 1 else "No"
    )


Student 1 Support Prediction:
Math Support: Yes
English Support: Yes
Attendance Support: No

Student 2 Support Prediction:
Math Support: No
English Support: No
Attendance Support: No

Student 3 Support Prediction:
Math Support: No
English Support: No
Attendance Support: No

Student 4 Support Prediction:
Math Support: No
English Support: No
Attendance Support: No


In [14]:
new_student = pd.DataFrame({
    "Attendance": [65],
  "MathScore":[89],
        "EnglishScore":[76],
        "QuizScore":[67],
        "MissedClasses": [4]
})
new_prediction = model.predict(new_student)

print(new_prediction)
prediction = new_prediction[0]

print("Student Support Prediction:")
print("Math Support:", "Yes" if prediction[0] == 1 else "No")
print("English Support:", "Yes" if prediction[1] == 1 else "No")
print("Attendance Support:", "Yes" if prediction[2] == 1 else "No")

[[0 0 0]]
Student Support Prediction:
Math Support: No
English Support: No
Attendance Support: No
